Fix/routes
FullStackkDev/Bookwriter-frontend pull request #9
Opened 2023-10-26 13:57 UTC by FullStackkDev

Create a new redux reducer for logging in and logging out the user.
Create a protected route function for checking authentication and navigating users according to authentication.
Add a new API file to get user data from the backend.

2023-10-26 14:04 UTC, marslan-ali requested changes

2023-10-26 14:04 UTC, marslan-ali commented on src/App.js
> +      {isAuthenticated && <Navbar />}
@FullStackkDev please define routes in separate file

2023-10-27 07:14 UTC, FullStackkDev commented on src/Redux/store/authSlice.js
> +    token: JSON.parse(getLocalStorage("user")) || null, // Get the token from local storage
This is wrong to store the user in a token store only the token in the key "token" or update the name.

2023-10-27 07:14 UTC, FullStackkDev commented on src/Redux/store/userSlice.js
> +
remove extra space

2023-10-27 10:44 UTC, FullStackkDev commented on src/Redux/store/userSlice.js
> +
Its prettier formatting. After all imports one line is blank.

2023-10-30 05:18 UTC, merged